---
title: "Racial Disparities at Kernan Middle School"
output: 
  html_notebook:
    theme: paper
    toc: yes
    toc_float: yes
---

```{r echo=FALSE}
if (!require(tidyverse)){
  install.packages("tidyverse", dependencies = TRUE)
  library(tidyverse)
}
```

# The data

Data about Kernan Middle School from the [Office for Civil Rights](https://ocrdata.ed.gov/Page?t=s&eid=266922&syk=8&pid=2275)

```{r echo=FALSE}
(tibble::tribble(
                            ~Race, ~Enrollment, ~InSchoolSuspension, ~OutofSchoolSuspension, ~GiftedandTalented, ~Algebra1Enrollment,
  "American Indian/Alaska Native",       0.002,               0.003,                      0,                  0,                   0,
                          "Asian",       0.074,               0.037,                      0,              0.111,               0.121,
                          "Black",       0.232,                0.37,                  0.395,              0.111,               0.212,
                       "Hispanic",       0.144,               0.148,                  0.158,              0.056,               0.061,
               "Pacific Islander",           0,                   0,                      0,                  0,                   0,
                    "Two or More",       0.061,               0.067,                  0.053,              0.111,               0.121,
                          "White",       0.489,               0.348,                  0.395,              0.611,               0.485
  ) -> dataset)

```
# Racial Disparities in the Gifted and Talented Program
```{r echo=FALSE}
# reshape for graphing
dataset %>%
  gather(metric, percentage,-Race) %>%
  filter(metric == "Enrollment" | metric == "GiftedandTalented") %>%
  ggplot(aes(x = percentage, y = Race)) +
  geom_line(aes(group = Race)) + 
  geom_point(aes(color=metric), size=4, alpha = .6) +
  scale_color_manual(values = c("#BE1C42", "#009CFD"), 
                     labels=c("% of Enrolled Students","% of Gifted and Talented Students")) +
  scale_x_continuous(labels=scales::percent_format(), limits = (c(0, 1))) +
  labs(title = "Kernan Middle School", subtitle = "Racial Disparities in the Gifted and Talented Program", x = "Source: https://ocrdata.ed.gov/Page?t=s&eid=266922&syk=8&pid=2275") +
  theme_minimal() + 
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank(),
        legend.position = "top",
        axis.title.y = element_blank())
```
# Racial Disparities in In-School Suspensions
```{r echo=FALSE}
# reshape for graphing
dataset %>%
  gather(metric, percentage,-Race) %>%
  filter(metric == "Enrollment" | metric == "InSchoolSuspension") %>%
  ggplot(aes(x = percentage, y = Race)) +
  geom_line(aes(group = Race)) + 
  geom_point(aes(color=metric), size=4, alpha = .6) +
  scale_color_manual(values = c("#BE1C42", "#009CFD"), 
                     labels=c("% of Enrolled Students","% of In-School Suspended Students")) +
  scale_x_continuous(labels=scales::percent_format(), limits = (c(0, 1))) +
  labs(title = "Kernan Middle School", subtitle = "Racial Disparities in In-School Suspensions", x = "Source: https://ocrdata.ed.gov/Page?t=s&eid=266922&syk=8&pid=2275") +
  theme_minimal() + 
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank(),
        legend.position = "top",
        axis.title.y = element_blank())
```
